In [1]:
import numpy as np

In [92]:
A = np.zeros([3 ,2])
A[0,0] = 1
A[0,1] = 2
A[1,0] = 3
A[1,1] = 4
A[2,0] = 5
A[2,1] = 6

In [74]:
np.mean(A, axis=0)

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [75]:
np.mean(A, axis=1)

array([[1.5, 1.5, 1.5, 1.5],
       [3.5, 3.5, 3.5, 3.5],
       [5.5, 5.5, 5.5, 5.5]])

In [76]:
np.mean(A, axis=-1)

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [77]:
def red(logits, reduction, axis=-1):
    if (reduction=="mean"):
        b = np.mean(logits, axis=axis)
    else:
        b = np.sum(logits, axis=axis)
    return b

In [78]:
red(A, "sum", axis=0)

array([[ 9.,  9.,  9.,  9.],
       [12., 12., 12., 12.]])

In [79]:
dimAxis = np.shape(A)
print(A)

[[[1. 1. 1. 1.]
  [2. 2. 2. 2.]]

 [[3. 3. 3. 3.]
  [4. 4. 4. 4.]]

 [[5. 5. 5. 5.]
  [6. 6. 6. 6.]]]


In [80]:
np.delete(A, np.arange(0, dimAxis[0]-1), axis=0)

array([[[5., 5., 5., 5.],
        [6., 6., 6., 6.]]])

In [69]:
dimAxis

(3, 2)

In [93]:
A

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [102]:
normalization = red(A, "sum", axis=0)
print(normalization)

[ 9. 12.]


In [104]:
A - np.log(normalization)

array([[-1.19722458, -0.48490665],
       [ 0.80277542,  1.51509335],
       [ 2.80277542,  3.51509335]])

In [109]:
A[range(2), [0,1]]

array([1., 4.])